Public Release for Fall24 meta-release
camaraproject/SimSwap pull request #148
Opened 2024-08-23 13:27 UTC by bigludo7

#### What type of PR is this?

Add one of the following kinds:

* subproject management

#### What this PR does / why we need it:

Related to issue #109 

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for reviewers:

Missing link for Test Statement for sim-swap

#### Changelog input

```
 Public release for sim-swap v1.0.0 and sim-swap-subscriptions v0.1.0

```

#### Additional documentation 

This section can be blank.

```
docs

```

2024-08-23 14:36 UTC, fernandopradocabrillo submitted a review, later dismissed

2024-08-23 14:43 UTC, hdamker reviewed
Some suggestions. Please add @camaraproject/release-management_maintainers if ready for review by Release Management

2024-08-23 14:43 UTC, hdamker commented on CHANGELOG.md
> +* add API-Name aka wild-card scope by @AxelNennker in https://github.com/camaraproject/SimSwap/pull/103
Not sure if this description would be understood by someone who wasn't involved in the discussion.

How about:
```suggestion
* Added the API name `sim-swap` as a scope to request access to both available endpoints by @AxelNennker in https://github.com/camaraproject/SimSwap/pull/103
```

2024-08-23 14:43 UTC, hdamker commented on CHANGELOG.md
> +* Make response properties "latestSimChange" and "swapped" required since they will always be returned [Issue 96](https://github.com/camaraproject/SimSwap/issues/96)
Propose to use past tense and link to PRs, not issues:

```suggestion
* Made response properties `latestSimChange` and `swapped` required since they will always be returned by @fernandopradocabrillo in https://github.com/camaraproject/SimSwap/pull/97
```

2024-08-23 14:43 UTC, hdamker commented on CHANGELOG.md
> +* Update SIM Swap  yaml to make the '+' mandatory for phoneNumber by @bigludo7 in https://github.com/camaraproject/SimSwap/pull/100
```suggestion
* Updated pattern to make the '+' mandatory for phoneNumber by @bigludo7 in https://github.com/camaraproject/SimSwap/pull/100
```

2024-08-23 14:43 UTC, hdamker commented on CHANGELOG.md
> +* phone number instead of MSISDN to follow communalities guidelines by @gregory1g in https://github.com/camaraproject/SimSwap/pull/116
```suggestion
* Replaced "MSISDN" with "phone number" in descriptions to follow Commonalities guidelines by @gregory1g in https://github.com/camaraproject/SimSwap/pull/116
```

2024-08-23 14:43 UTC, hdamker commented on CHANGELOG.md
> +* Remove unused errors and align with commonalities errors by @fernandopradocabrillo in https://github.com/camaraproject/SimSwap/pull/126
```suggestion
* Removed unused errors and align with Commonalities error definitions by @fernandopradocabrillo in https://github.com/camaraproject/SimSwap/pull/126
```

2024-08-23 14:43 UTC, hdamker commented on CHANGELOG.md
> +**sim-swap-subscriptions v0.1.0 is the first initial version for CAMARA Sim Swap subscription API**
```suggestion
**sim-swap-subscriptions v0.1.0 is the first initial version for the CAMARA Sim Swap Subscriptions API**
```
Not sure if you want to use CAMARA here (it is not mentioned above for SimSwap)

2024-08-23 14:43 UTC, hdamker commented on CHANGELOG.md
> +* Initial contribution of the API definition for sim swap subscription allowing API consumer to subscribe to get notified when a sim swap occurs on a device.
```suggestion
* Initial contribution of the API definition for Sim Swap Subscriptions allowing API consumers to subscribe to get notified when a sim swap occurs on a device.
```

2024-08-23 14:43 UTC, hdamker commented on CHANGELOG.md
> +* Update yaml to make the '+' mandatory for phoneNumber by @bigludo7 in https://github.com/camaraproject/SimSwap/pull/100
```suggestion
* Update pattern to make the '+' mandatory for phoneNumber by @bigludo7 in https://github.com/camaraproject/SimSwap/pull/100
```

2024-08-23 14:43 UTC, hdamker commented on code/API_definitions/sim-swap-subscriptions.yaml
> +  - url: '{apiRoot}/sim-swap-subscriptions/v0'
API versioning guideline:
```suggestion
  - url: '{apiRoot}/sim-swap-subscriptions/v0.1'

```

2024-08-23 14:43 UTC, hdamker commented on documentation/API_documentation/sim-swap-subscriptions-API-Readiness-Checklist.md
>  |  4 | API versioning convention applied            |   M   |         M         |    M    |    M   |  Y   |  Y  |
comments are duplicates of the status

```suggestion
|  2 | Design guidelines from Commonalities applied |   O   |         M         |    M    |    M   |  Y   |       |
|  3 | Guidelines from ICM applied                  |   O   |         M         |    M    |    M   |  Y   |     |
|  4 | API versioning convention applied            |   M   |         M         |    M    |    M   |  Y   |     |
```

2024-08-23 14:43 UTC, hdamker commented on documentation/API_documentation/sim-swap-subscriptions-API-Readiness-Checklist.md
> +| 12 | Previous public release was certified        |   O   |         O         |    O    |    M   |  N   | N    |
as previous comment

```suggestion
|  6 | User stories                                 |   O   |         O         |    O    |    M   |  N   |    |
|  7 | Basic API test cases & documentation         |   O   |         M         |    M    |    M   |  Y   | [link](/code/Test_definitions/sim-swap-subscriptions.feature) |
|  8 | Enhanced API test cases & documentation      |   O   |         O         |    O    |    M   |  N   |      |
|  9 | Test result statement                        |   O   |         O         |    O    |    M   |  N   |     |
| 10 | API release numbering convention applied     |   M   |         M         |    M    |    M   |  Y   |      |
| 11 | Change log updated                           |   M   |         M         |    M    |    M   |  Y   | [link](/CHANGELOG.md) |
| 12 | Previous public release was certified        |   O   |         O         |    O    |    M   |  N   |      | 
```

2024-08-23 14:43 UTC, hdamker commented on documentation/API_documentation/sim-swap-subscriptions-API-Readiness-Checklist.md
>  |----|----------------------------------------------|:-----:|:-----------------:|:-------:|:------:|:----:|:----:|
Deviates from the template, but comments column don't need to be centered:

```suggestion
|----|----------------------------------------------|:-----:|:-----------------:|:-------:|:------:|:----:|------|
```

2024-08-23 14:43 UTC, hdamker commented on code/API_definitions/sim-swap-subscriptions.yaml
> +  - url: '{apiRoot}/sim-swap-subscriptions/v0'
This one is mandatory to be corrected

2024-08-23 14:58 UTC, bigludo7 commented
Huge thanks @hdamker for the review.

2024-09-03 11:39 UTC, jlurien requested changes
* Also correct: Given the resource "/sim-swap-subscriptions/v0/subscriptions" -> Given the resource "/sim-swap-subscriptions/v0.1/subscriptions"

2024-09-03 11:39 UTC, jlurien commented on code/Test_definitions/retrieve-sim-swap-date.feature
>      Given the resource "sim-swap/v0/retrieve-date"
It must be v1

2024-09-03 11:39 UTC, jlurien commented on code/Test_definitions/check-sim-swap.feature
>      Given the resource "sim-swap/v0/check"
It must be v1

2024-09-03 11:39 UTC, jlurien commented on documentation/API_documentation/sim-swap-subscriptions-API-Readiness-Checklist.md
> +|  5 | API documentation                            |   M   |         M         |    M    |    M   |  Y   | Embed documentation into API spec - [link](/code/API_definitions/sim-swap.yaml) |
```suggestion
|  5 | API documentation                            |   M   |         M         |    M    |    M   |  Y   | Embedded documentation into API spec - [link](/code/API_definitions/sim-swap.yaml) |
```

2024-09-03 12:33 UTC, bigludo7 commented on code/Test_definitions/retrieve-sim-swap-date.feature
>      Given the resource "sim-swap/v0/retrieve-date"
Done :)

2024-09-03 12:34 UTC, bigludo7 commented on code/Test_definitions/check-sim-swap.feature
>      Given the resource "sim-swap/v0/check"
Done

2024-09-03 12:34 UTC, bigludo7 commented
@jlurien Thanks for the review. Update done for the 3 files.

2024-09-04 12:50 UTC, jlurien commented
Let's wait to decision on https://github.com/camaraproject/ReleaseManagement/issues/89 to merge this

2024-09-05 16:23 UTC, tanjadegroot commented
Please see https://github.com/camaraproject/ReleaseManagement/issues/89 on how to update the Test result statement in the API readiness checklist for this Fall24 meta-release.

2024-09-05 16:41 UTC, bigludo7 commented
@jlurien @tanjadegroot aligned for the Test Statement.

2024-09-06 09:39 UTC, jlurien approved these changes
Release PR approved (on behalf of Release Management)

PR can now be merged and release r1.2 created. Please update https://wiki.camaraproject.org/display/CAM/SimSwap+API+Release+Tracking with date for M4 and link to r1.2 when it is created. Thanks

2024-09-06 09:46 UTC, bigludo7 commented
Thanks @jlurien for the review :)
As soon as @fernandopradocabrillo  and/or @hdamker (for Axel) approve I merge & update the confluence.

2024-09-06 15:27 UTC, merged