[Sim-Swap-Subscription]: Add TerminationReason SUBSCRIPTION_DELETED
camaraproject/SimSwap pull request #177
Opened 2024-11-19 12:46 UTC by daniel-dierich

#### What type of PR is this?

Add one of the following kinds:

* enhancement/feature

#### What this PR does / why we need it:

Adds TerminationReason SUBSCRIPTION_DELETED

#### Which issue(s) this PR fixes:

Fixes #172

#### Special notes for reviewers:

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

2024-12-08 14:29 UTC, bigludo7 approved these changes
LGTM

2024-12-16 13:38 UTC, fernandopradocabrillo approved these changes

2024-12-16 14:14 UTC, bigludo7 requested changes
Change version to wip lines 64 & 71

2024-12-16 15:19 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-subscriptions.yaml
> +  - url: '{apiRoot}/sim-swap-subscriptions/wip'
```suggestion
  - url: '{apiRoot}/sim-swap-subscriptions/vwip'

```

2024-12-16 15:20 UTC, fernandopradocabrillo approved these changes
LGTM

2024-12-16 15:21 UTC, merged