Sim swap alignement with  commonalities 0.5
camaraproject/SimSwap pull request #180
Opened 2024-12-23 15:51 UTC by bigludo7

#### What type of PR is this?

Add one of the following kinds:

* enhancement/feature

#### What this PR does / why we need it:

Alignement of sim_swap.yaml, sim_swap-retrieveDate.feature and sim_swap-check.feature  with commonalities 0.5 rules.
See detail in release note

#### Which issue(s) this PR fixes:

Fixes #161 

#### Special notes for reviewers:

This is breaking change.

#### Changelog input

```
release-note
sim_swap.yaml:
- Change error structure definition to normalize error & status
- Update error code to introduce 429
- Remove 5xx errors
- Change in 422 code
- Add 3-legged token examples
- Improve documentation part

sim_swap-retrieveDate.feature:
- update test case scenario for 422
- Add optional test case for 401 AUTHENTICATION_REQUIRED

sim_swap-check.feature:
- update test case scenario for 422
- Add optional test case for 401 AUTHENTICATION_REQUIRED
```

#### Additional documentation 

This section can be blank.

```
docs

```

2025-01-06 07:24 UTC, gregory1g requested changes

2025-01-06 07:24 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +    This API requires the API consumer to identify a device as the subject of the API as follows:
For SimSwap a subject of the API is a phone number, not a device. The "device-centric" language is misleading.

2025-01-06 07:24 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +                message: "{{field}} is not consistent with access token."
What "field" other than the phoneNumber can it be?

2025-01-06 07:24 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +        phoneNumber: "+346661113334"
Is there any reason to keep phone number in the response at all?
This is a poll API - the invoker sent phoneNumber in the request, there is no value to send it back in the response.
Suggestion remove it from the repsonse completely.

From the backward compatibility point of view this is a gray area anyway.

2025-01-06 07:24 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +    - If the subject can be identified from the access token and the optional `phoneNumber` identifier is also included in the request, then the server will return an error with the `422 UNNECESSARY_
I agree with the logic of the change, but this is a not-backward compatible change. Currently one may send 3-legged token and the phoneNumber (even if this is not recommended),  with this change this will cause a error.

2025-01-06 07:24 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +            examples:
I did not found any formal description saying that phoneNumber must not be included in the response when 3-leged token is used. If such a rule is introduced, it is must be clearly described.
Many consider removing an optional response parameter as a not backward compatible change.

2025-01-06 17:24 UTC, bigludo7 commented on code/API_definitions/sim-swap.yaml
> +            examples:
I do not follow you @gregory1g - in previous version the phoneNumber was **not** in the response.

2025-01-06 17:27 UTC, bigludo7 commented on code/API_definitions/sim-swap.yaml
> +    - If the subject can be identified from the access token and the optional `phoneNumber` identifier is also included in the request, then the server will return an error with the `422 UNNECESSARY_
Agree we have a breaking change here but we have to follow commonalities. Indeed, If you use 3-legs access token with a phoneNumber in the body you'll have a 422 UNNECESSARY_IDENTIFIER while previously it worked.

As a reminder we introduced this to avoid 'hidden' number verification

2025-01-06 17:28 UTC, bigludo7 commented on code/API_definitions/sim-swap.yaml
> +        phoneNumber: "+346661113334"
Humm...we do not the phoneNumber in the response - only in the request.

2025-01-06 17:28 UTC, bigludo7 commented on code/API_definitions/sim-swap.yaml
> +    This API requires the API consumer to identify a device as the subject of the API as follows:
Agreed. I will apply.

2025-01-06 17:33 UTC, bigludo7 commented on code/API_definitions/sim-swap.yaml
> +                message: "{{field}} is not consistent with access token."
I followed what is described in the [CAMARA_common.yaml](https://github.com/camaraproject/Commonalities/blob/main/artifacts/CAMARA_common.yaml) 

I tend to think that this error should not be triggered in our case because if you pass a 3-legs access token identifying the phone number and a phone number in the body the 422 UNNECESSARY_IDENTIFIER must be triggered.

2025-01-07 06:10 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +            examples:
You are right. It looks like I checked wrong swagger file.
Still, is phone number really needed in the response in case of 2-legged? What for? The invoker provided the phoneNumber it is after in the request already, the response must deliver information about the requested phoneNumber. And if phone number is really needed in the successful response to re-check request/response ,match, why it is not included in all error responses as well?

2025-01-07 06:14 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +    - If the subject can be identified from the access token and the optional `phoneNumber` identifier is also included in the request, then the server will return an error with the `422 UNNECESSARY_
The purpose of my comment was to highlight this, and make sure that the consequences of new commonalities are not overlooked.

2025-01-07 06:24 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +        phoneNumber: "+346661113334"
You are right. something went wrong on my side here. ignore my comment.

2025-01-07 06:30 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +                message: "{{field}} is not consistent with access token."
Yes, I understood that you follow commonalities. But should we really copy paste its wording 1:1 when we know better. A developer will read this text and can be confused.

And you are right - with the change this PR introduces, this check will not be executed: 422 to be returned without checking if both match or not. Let's remove it.

2025-01-07 08:11 UTC, bigludo7 commented on code/API_definitions/sim-swap.yaml
> +                message: "{{field}} is not consistent with access token."
Yes make sense for me. to remove ut but I would like to hear from @fernandopradocabrillo before to proceed.

Fernando do you think we can remove 403 INVALID_TOKEN_CONTEXT ? as we do not see when this error will be triggered.

2025-01-09 07:18 UTC, bigludo7 commented
@fernandopradocabrillo @gregory1g  Following https://github.com/camaraproject/Commonalities/issues/369 discussion I think it's fair to remove 403 INVALID_TOKEN_CONTEXT example in the yaml.

May I ask you to review this new proposal soon as we have to prepare the RC candidate before Jan17th. We can still modify after but we have to achieve the milestone.

2025-01-09 09:05 UTC, bigludo7 commented on code/API_definitions/sim-swap.yaml
> +    # Identifying the device from the access token
You're right. I fixed line 49 but missed this one. I will fix. Thanks

2025-01-09 09:09 UTC, bigludo7 commented on code/API_definitions/sim-swap.yaml
> +                message: Either out of resource quota or reaching rate limiting.
This is a good comment @gregory1g but it should be triggered to commonalities first as here I used what we have defined for commonalities v0.5 (in https://github.com/camaraproject/Commonalities/blob/main/artifacts/CAMARA_common.yaml)

I suggest to not change this for this release to keep alignement with Commonalities 0.5 and then change this depending of commonalities outcome for next iteration. Work for you?

2025-01-09 09:12 UTC, bigludo7 commented on code/API_definitions/sim-swap.yaml
> +    # Identifying the device from the access token
done

2025-01-09 09:16 UTC, bigludo7 commented on code/API_definitions/sim-swap.yaml
> +              description: An identifier is not included in the request and the device or phone number identification cannot be derived from the 3-legged access token
This is generic.
I followed commonalities guideline see [here](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#61-standardized-use-of-camara-error-responses).

I suggest @gregory1g that you post your comment in commonalities as it makes sense.

2025-01-09 11:36 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +              description: An identifier is not included in the request and the device or phone number identification cannot be derived from the 3-legged access token
created an issue there: https://github.com/camaraproject/Commonalities/issues/370

2025-01-09 11:47 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +                message: Either out of resource quota or reaching rate limiting.
ok. Added https://github.com/camaraproject/Commonalities/issues/372

2025-01-10 10:04 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +              description: An identifier is not included in the request and the device or phone number identification cannot be derived from the 3-legged access token
according to Eric, commonality's "description" is not a error message to be send, it is a description for the reader of the table in the document. While example of the message is in the "Message example" column. An this is just an example, different API can use different text

2025-01-10 10:05 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +                message: Either out of resource quota or reaching rate limiting.
according to Eric "Message example" column where the text came from us just an example, different API can use different text. So, there is no need to use exactly the same text as in the commonalities.

2025-01-10 10:56 UTC, bigludo7 commented on code/API_definitions/sim-swap.yaml
> +                message: Either out of resource quota or reaching rate limiting.
Thanks @gregory1g 
As the implementation is free to change the `description` do we have to provide here something different from other API for 429?
I 'm fine to provide 2 exemple if is it a blocking point for you but me preference is to keep as it.
+ @fernandopradocabrillo

2025-01-10 13:48 UTC, bigludo7 commented on code/API_definitions/sim-swap.yaml
> +                message: Either out of resource quota or reaching rate limiting.
Done

2025-01-10 14:46 UTC, bigludo7 commented on code/API_definitions/sim-swap.yaml
> +              description: An identifier is not included in the request and the device or phone number identification cannot be derived from the 3-legged access token
I've reworked the yaml & TC to add all clarification - please review.

2025-01-13 06:53 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +    This API requires the API consumer to identify a device (via its phone number) as the subject of the API as follows:
"to identify a device" this is not the case, the API does not need to identify a device at all. MSIDN is subscription ID, not a device ID. And the API implementation does not need to identify the device either.
Considering that API description targets application developers, using "device" is rather misleading. It makes a reader think that this API target exact phone unit like geo location APIs do.

2025-01-13 06:53 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +    - When the API is invoked using a two-legged access token, the subject will be identified from the optional `phoneNumber` identifier, which therefore MUST be provided.
"the subject will be identified from the optional `phoneNumber` identifier" says that the phoneNumner is not the subject of the API, but just a helper to identify the device. This is confusing. The original terminology was simpler to understand. Especially when one also reads documentation for other API which really target a device.

2025-01-13 06:53 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +    - If the subject cannot be identified from the access token and the optional `phoneNumber` identifier is not included in the request, then the server will return an error with the `422 MISSING_ID
Suggestion: use "phoneNumer" instead of "subject" - it is still a single word and it is simpler to understand.

2025-01-15 08:28 UTC, bigludo7 commented on code/API_definitions/sim-swap.yaml
> +    - When the API is invoked using a two-legged access token, the subject will be identified from the optional `phoneNumber` identifier, which therefore MUST be provided.
Fixed accordingly

2025-01-15 08:28 UTC, bigludo7 commented on code/API_definitions/sim-swap.yaml
> +    This API requires the API consumer to identify a device (via its phone number) as the subject of the API as follows:
Fixed accordingly

2025-01-15 17:05 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap.yaml
> +    - If the subject cannot be identified from the access token and the optional `phoneNumber` identifier is not included in the request, then the server will return an error with the `422 MISSING_ID
```suggestion
    - If the phoneNumber cannot be identified from the access token and the optional `phoneNumber` identifier is not included in the request, then the server will return an error with the `422 MISSING_IDENTIFIER` error code.
```

2025-01-15 17:05 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap.yaml
> +    - If the subject can be identified from the access token and the optional `phoneNumber` identifier is also included in the request, then the server will return an error with the `422 UNNECESSARY_
```suggestion
    - If the phoneNumber can be identified from the access token and the optional `phoneNumber` identifier is also included in the request, then the server will return an error with the `422 UNNECESSARY_IDENTIFIER` error code. This will be the case even if the same device is identified by these two methods, as the server is unable to make this comparison.
```

2025-01-15 17:11 UTC, fernandopradocabrillo submitted a review, later dismissed
LGTM

2025-01-15 17:36 UTC, eric-murray commented on code/API_definitions/sim-swap.yaml
> +    This API requires the API consumer to identify a device (via its phone number) as the subject of the API as follows:
> using "device" is rather misleading

One of the advantages of the CAMARA approach is that application developers can use APIs such as SIM Swap without knowing (or learning) the MSISDN at all. All they need to do is identify a device using the subscription, and capture its IP address. I think ruthlessly expunging "device" from our documentation and baking in "phone number" mean this possibility gets overlooked.

It would be nice if we could come up with some "developer friendly" formulation of words which also captures this possibility, as there will be use cases out there that would benefit from this approach if only developers were aware of it.

2025-01-15 19:34 UTC, bigludo7 commented on code/API_definitions/sim-swap.yaml
> +    This API requires the API consumer to identify a device (via its phone number) as the subject of the API as follows:
@eric-murray To be sure to follow you - as in the body we can only use the phone number  - you want to highlight the point that via the 3-legged token we can value in the `login-hint` other identifier like ip?

2025-01-15 20:32 UTC, eric-murray commented on code/API_definitions/sim-swap.yaml
> +    This API requires the API consumer to identify a device (via its phone number) as the subject of the API as follows:
@bigludo7
No, it was just a general comment - I'm not expecting the documentation to be updated because of it.

Using a 2-legged access token and explicit identifier will very much be the exception for CAMARA APIs, and yet it is the definition of the explicit identifier that dominates the API description. For the normal case of a 3-legged access token, the token itself is not classified as a "device" token or "phone number" token. The very same token could be used for both a "phone number" API (such as SIM Swap) and a "device" API (such as Device Status).

If 3-legged tokens were the only option, we would not have to go through these mental gymnastics of documenting an API as either a "device" API or a "phone number" API. It is to be hoped that we can come to some agreement on a common formulation for the documentation that reveals this capability to developers without confusing them.

2025-01-16 06:43 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +    This API requires the API consumer to identify a device (via its phone number) as the subject of the API as follows:
@eric-murray 
> "All they need to do is identify a device using the subscription, and capture its IP address." 

not exactly, SimSwap API answers the question "if a SIM Card was swapped for the MSISDN". MSISDN is a target of the API not a device. SimSwap can potentially processes an IP as an input, but then it will need to find MSISDN associated with this device first and then do the checks for this MSISDN. For example, if an additional SIM was issued for the given MSISND and used in completely different device, it is still a SimSwap.

2025-01-16 08:47 UTC, fernandopradocabrillo approved these changes

2025-01-16 10:01 UTC, eric-murray commented on code/API_definitions/sim-swap.yaml
> +    This API requires the API consumer to identify a device (via its phone number) as the subject of the API as follows:
> SimSwap can potentially processes an IP as an input

For a 3-legged access token, the "processing" will already have been done. The SIM Swap API itself does not need to do anything different.

I take the point that IP as a device identifier is not persistent. An API consumer cannot capture the IP address and expect to use that the following week to check the SIM Swap status of the associated subscription. But if they immediately obtain an access token for that IP, then they can check the SIM Swap status for the subscription used by that device, all without even knowing what the MSISDN is.

It is this possibility I think gets overlooked - using "phone number" APIs without knowing the phone number.

2025-01-16 10:21 UTC, gregory1g commented on code/API_definitions/sim-swap.yaml
> +    This API requires the API consumer to identify a device (via its phone number) as the subject of the API as follows:
my point was that SimSwap does not target a device, it targets an MSISDN.

2025-01-16 12:19 UTC, bigludo7 commented on code/API_definitions/sim-swap.yaml
> +    This API requires the API consumer to identify a device (via its phone number) as the subject of the API as follows:
@gregory1g @eric-murray Does this discussion prevent me to merge this PR? with the M3 at the horizon we need to move forward for the yaml & work on the other asset. I can try to copy paste your comment in the discussion?

2025-01-16 12:50 UTC, eric-murray commented on code/API_definitions/sim-swap.yaml
> +    This API requires the API consumer to identify a device (via its phone number) as the subject of the API as follows:
@bigludo7
No changes needed, just proceed with the M3 as planned.

Probably the full range of use cases that can be supported by an API can be better advertised through developer portals rather than the YAML documentation anyway. But we can maybe think later on how we can better document what a developer needs to know or needs access to in order to use an API.

2025-01-16 12:55 UTC, gregory1g commented
lgtm

2025-01-16 12:55 UTC, gregory1g approved these changes

2025-01-16 15:10 UTC, merged