Sim Swap Notification subscription yaml
camaraproject/SimSwap pull request #60
Opened 2023-10-02 15:52 UTC by bigludo7

#### What type of PR is this?

* enhancement/feature

#### What this PR does / why we need it:

Add a new API to manage sim swap notification subscription & notification.
yaml aligned with CAMARA commonalities design guidelines.

#### Which issue(s) this PR fixes:

Fixes #47 

#### Special notes for reviewers:

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

2023-10-03 12:20 UTC, fernandopradocabrillo reviewed
@bigludo7 
I leave a few initial comments to discuss. 

Thanks for the PR!

2023-10-03 12:20 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +                  $ref: '#/components/schemas/SubscriptionInfo'
The same comment as in the creation body, the suscriptionDetails should be required in the responses of the GET operations.

The subscriptionId should be required too. Otherwise how would I be able to get the details of a particular subscription?

And, maybe the `startsAt` field should be required too. Since we have both models sync/async:
- If the response is async then the field is not present in the response
- If the response is sync, then it means that the subscription has already been created so it has a `startsAt` date and should be required since the information is available.

2023-10-05 07:23 UTC, gregory1g commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +          $ref: '#/components/schemas/SimSwapEventType'
should we refence RoamingNotificationEventType here as well?

2023-10-05 10:20 UTC, bigludo7 commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +          $ref: '#/components/schemas/SimSwapEventType'
I will prefer not. If we list all event type in all API that will be complicated to maintain.
Perhaps we should provide 'somewhere' a listing of all event type managed within our CAMARA APIs?

2023-10-05 10:21 UTC, bigludo7 commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +      - sim-swap:subscriptions:create
Agree - fixed.

2023-10-05 10:23 UTC, bigludo7 commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +        subscriptionDetail:
Yes got your point. As the subscription/notification is still 'fresh' I guess we're still testing it. I changed the cardinality to mandatory.

2023-10-05 10:23 UTC, bigludo7 commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +                  $ref: '#/components/schemas/SubscriptionInfo'
Same previous

2023-10-05 10:29 UTC, gregory1g commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +          $ref: '#/components/schemas/SimSwapEventType'
But currently we list only exact one of them. API client must know what events it can receive and implement corresponding logic. One can keep the list open, but at least base type of events must be described. Events like "even notification subscription ends" and "MSISDN subscription ends" are critically important and must be included in the "base" list of event types.
All above if IMO :)

2023-10-05 12:20 UTC, bigludo7 commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +          $ref: '#/components/schemas/SimSwapEventType'
@gregory1g Thanks for the feedback
We have only one `type` for subscribtion but 2 `type` are managed by notification.  Indeed `org.camaraproject.sim-swap.v0.subscription-ends` is also described in this yaml. We do not plan to provide subscription for this one and send them automatically once the subscription terminates (for any reason). This is described in the doc part.

We should add in this documentation than the same resource for subscription as notification are managed for all other CAMARA APIs.

2023-10-09 09:16 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +      - sim-swap:subscriptions:create
@bigludo7 
if we already have the security property in every operation, the global security is redundant right? I think we can remove it

2023-10-09 09:28 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +        - openId::
```suggestion
        - openId:

```

2023-10-09 09:28 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +        - openId::
```suggestion
        - openId:

```

2023-10-09 09:28 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +        - openId::
```suggestion
        - openId:

```

2023-10-09 09:28 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +        - openId::
```suggestion
        - openId:

```

2023-10-09 19:05 UTC, bigludo7 commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +      - sim-swap:subscriptions:create
@fernandopradocabrillo Which one do you think we can remove ? I followed https://swagger.io/docs/specification/authentication/openid-connect-discovery/ pattern.

2023-10-17 05:22 UTC, gregory1g commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +    It is used when the subscription expire time (required by the requester) has been reached or if the API server has to stop sending notification prematurely.
"if the API server has to stop sending notification prematurely." sounds a bit unclear, what about using more simple wording like "if the API server has to terminate subscription (e.g. when the corresponding phone number is not served by the operator anymore)"?

2023-10-17 05:35 UTC, gregory1g commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +      - sim-swap:subscriptions:create
Do we need independent scopes here?
From the end user privacy point of view, allow someone to subscribe to simswap is equal to allow someone to read simswap timestamp. Or, at least a permission to "subscribe" includes permission to read. Like end user revokes permission to read their SimSwap information, this logically also revokes permission to be notified about such events.  This is an API specific logic, and it is too risky to completely delegate it to Auth/Consent configuration.

2023-10-17 07:21 UTC, bigludo7 commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +      - sim-swap:subscriptions:create
@gregory1g This is a fair comment. Could we consider from a privacy perspective that checking now is same than checking for a coming period of x days? 
I tend to agree with you.
@fernandopradocabrillo @DT-DawidWroblewski : could you please provide your view here.

2023-10-17 10:25 UTC, gregory1g commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +          $ref: '#/components/schemas/SimSwapEventType'
ok.

2023-10-17 10:30 UTC, gregory1g commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +          enum: ["SUBSCRIPTION_EXPIRED", "NETWORK_TERMINATED"]
as mentioned above "NETWORK_TERMINTAED" covers a server side termination for whatever reason. Two questions here:
1) Is "NETWORK_TERMINTAED" a self-explaining term for a server initiated termination? One can expect that user terminated is different from network terminated.
2) shouldn't we add a possibility for an MNO to provide an optional a human readable text description explaining the reason behind server side termination?

2023-10-17 10:31 UTC, gregory1g commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +        id:
What about subscription ID, shouldn't it be included in the event as well?

2023-10-23 11:55 UTC, bigludo7 reviewed
Answered + updated following @gregory1g review.

2023-10-23 11:55 UTC, bigludo7 commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +        id:
Yes - It should be part of the Data structure - I add it.

2023-10-23 11:55 UTC, bigludo7 commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +          enum: ["SUBSCRIPTION_EXPIRED", "NETWORK_TERMINATED"]
1. Not sure to get it. You want me to add USER_TERMINATED ?
2. Yes make sense - I've add a `terminationDescription` attribute.

2023-10-23 12:13 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +      - sim-swap:subscriptions:create
and isn't it possible to have permission to read but not to subscribe to the notification?

2023-10-23 12:15 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +      - sim-swap:subscriptions:create
@bigludo7 
We can have the security property in every operation or have it global. I think it is better to have it in every endpoint so we can specify the scope that applies to each operation properly

2023-10-23 12:31 UTC, gregory1g commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +      - sim-swap:subscriptions:create
permission to read, but not to subscribe is rather questionable, but still could be needed.
however, permission to subscribe without permission to read sounds like an dangerous security inconsistency

2023-10-23 12:35 UTC, gregory1g commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +          enum: ["SUBSCRIPTION_EXPIRED", "NETWORK_TERMINATED"]
1. I dot think that we need to be introduce "user terminated" here. But NETWORK_TERMINTAED sounds too narrow. I suggest to consider a more generic term which covers everything which is initiated by the server side, either it is network as such, or user his/her self, or contract between application and MNO or even security conserns.

2023-11-02 17:14 UTC, bigludo7 commented
Hello @gregory1g 
May I ask you to check the answer provided to your comments and let me know if some of them need additional attention. Thanks for your help.

2023-11-02 18:29 UTC, fernandopradocabrillo reviewed
@bigludo7 
I leave you a few comments I've found in a more detailed review. Some are suggestions and some are small fixes.

2023-11-02 18:29 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +      - sim-swap:subscriptions:create
this hole black can be removed since we have the security property in every operation

2023-11-02 18:29 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +
```suggestion
```

2023-11-02 18:29 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +
```suggestion
```

2023-11-02 18:29 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +
```suggestion
```

2023-11-02 18:29 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +                    message: "Expected property is missing: eventSubscriptionId"
I think there is no need to include this example, I haven't seen it in other camara APIs either. But not a problem from my side if you want to keep it

2023-11-02 18:29 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +
```suggestion
```

2023-11-02 18:29 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +            type: string
This can be moved to the components section so it can be reused in the GET too

2023-11-02 18:29 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +                    message: "Expected property is missing: eventSubscriptionId"
same comment here

2023-11-02 18:29 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +    #      in: query
we can delete this block

2023-11-02 18:29 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +    (FAQs will be added in a later version of the documentation)
```suggestion
This API provides the customer with the ability to subscribe to events related to a sim swap operation performed on an associated phone number.

    # Introduction

    This API empowers service providers and network operators with a seamless mechanism for managing and monitoring SIM card swaps, a process often used in legitimate device upgrades or replacements but also susceptible to abuse in fraudulent activities.

    # Relevant terms and definitions

    * **SIM swap**:
    A SIM swap is a process in which a mobile phone user's current SIM card is deactivated or replaced with a new one. This is typically done by contacting the user's mobile service provider and requesting a new SIM card for various reasons, such as a lost or damaged SIM card, upgrading to a new phone, or changing phone numbers while keeping the same device.

    # API Functionality

    This API allows to manage client subscriptions to notification events published by the Sim Swap resource server at the URL provided when the subscription is created.

    The API exposes following capabilities:
      * **/subscriptions**: This endpoint has two operations, one that allows to retrieve the list of Sim Swap event subscriptions and another one to create new event subscriptions.
      * **/subscriptions/{subscriptionId}**: This endpoint also has two operations, one that allows to retrieve a particular event subscription by id and another one to delete an event subscription also using the id.

    ## Sim Swap notification subscription

    Theses endpoints allow to manage notification subscription on Sim Swap event. 
    The CAMARA subscription model is detailed in the CAMARA API design guideline document and follows Cloudevents specification.

    It is mandatory in the subscription to provide the event `type` to be subscribed.

    Only one event ``type`` is managed for this API: 
      - ``org.camaraproject.sim-swap.v0.swapped`` - Event triggered when a sim swap occurs on the associated phoneNumber

    Note: Additionally to these list, ``org.camaraproject.sim-swa.v0.subscription-ends`` notification `type` is sent when the subscription ends. 
    This notification did not requires dedicated subscription. 
    It is used when the subscription expire time (required by the requester) has been reached or if the API server has to terminate subscription (e.g. when the corresponding phone number is not served by the operator anymore). 

    ### Notification callback

    This endpoint describes the event notification received on subscription listener side when the event occurred. As for subscription, detailed description of the event notification is provided in the CAMARA API design guideline document.

    **WARNING**: This callback endpoint must be exposed on the listener side as `POST /{$request.body#/webhook/notificationUrl}`
      will be posted by the sim swap resource server to the webhook url provided by notification  listener.

    ## Further info and support

    (FAQs will be added in a later version of the documentation)
```

2023-11-02 18:29 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +    (FAQs will be added in a later version of the documentation)
I added a few more details to the description, just a suggestion to complete a little bit more 😄

2023-11-02 18:29 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +
```suggestion
```

2023-11-02 18:29 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +      description: Event detail structure for ROAMING_ON & ROAMING_OFF event
A copy&paste typo

```suggestion
      description: Event detail structure for SWAPPED event

```

2023-11-02 18:40 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +  title: Sim Swap Notification Subscription
```suggestion
  title: Sim Swap Notification Subscriptions

```

2023-11-02 18:40 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +        description: Base path for the sim swap notification subscription API
```suggestion
        description: Base path for the sim swap notification subscriptions API

```

2023-11-05 16:32 UTC, bigludo7 reviewed
Thanks @fernandopradocabrillo for your review. I have updated the yaml accordingly (except the error message that I kept).

2023-11-06 06:37 UTC, gregory1g commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +      - sim-swap:subscriptions:read
Using independent scopes we delegate permission consistency validation to consent management or to the end user.
When a user revokes their "read my SimSwap info" for app XYZ, it is user responsibility other ways XYZ can read their SimSwap data (e.g. via subscription).

2023-11-06 08:22 UTC, bigludo7 commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +      - sim-swap:subscriptions:read
Hello @gregory1g 
For me the simswap and the subscription are 2 different entities. As subscription is a distinct entity it makes sense to have distinct scope to manage it but worth to be discussed.
As we should have same discussion in subscription for device location and device status probably better to bring this discussion to commonalities. 

If a user revokes their "read my SimSwap info" for app XYZ, it is Telco commitment to terminate app XYZ subscription (if any) and prevent any sim swap data sharing with XYZ.

2023-11-06 12:31 UTC, fernandopradocabrillo reviewed
@bigludo7 
A few format-related additional comments.

2023-11-06 12:31 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +          $ref: '#/components/responses/Generic503'
The HTTP error codes must be in quotes. [Source](https://swagger.io/specification/v3/#responses-object)

```suggestion
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionInfo'
        "202":
          description: Request accepted to be processed. It applies for async creation process.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionAsync'
        "400":
          $ref: '#/components/responses/Generic400'
        "401":
          $ref: '#/components/responses/Generic401'
        "403":
          $ref: '#/components/responses/Generic403'
        "409":
          $ref: '#/components/responses/Generic409'
        "500":
          $ref: '#/components/responses/Generic500'
        "503":
          $ref: '#/components/responses/Generic503'

```

2023-11-06 12:31 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +          $ref: '#/components/responses/Generic503'
```suggestion
        "200":
          description: List of event subscription details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriptionInfo'
        "400":
          $ref: '#/components/responses/Generic400'
        "401":
          $ref: '#/components/responses/Generic401'
        "403":
          $ref: '#/components/responses/Generic403'
        "500":
          $ref: '#/components/responses/Generic500'
        "503":
          $ref: '#/components/responses/Generic503'

```

2023-11-06 12:31 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +        400:
```suggestion
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionInfo'
        "400":

```

2023-11-06 12:31 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +        503:
```suggestion
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
        "503":

```

2023-11-06 12:31 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +        400:
```suggestion
        "204":
          description: event subscription deleted
        "202":
          description: Request accepted to be processed. It applies for async deletion process.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionAsync'
        "400":
```

2023-11-06 12:31 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +        503:
```suggestion
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
        "503":
```

2023-11-06 12:45 UTC, fernandopradocabrillo commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +                $ref: '#/components/schemas/SubscriptionInfo'
@bigludo7 
One doubt here, in case I've missed something, why do we have the `phoneNumber` as optional in the request body?

And, even if we have it optional in the request, shouldn't it be required in the response? I think the response must give the complete information of the subscription. Applies the same for the GET endpoints

2023-11-06 16:32 UTC, bigludo7 reviewed
Changed cardinality for phoneNumber as suggested by @fernandopradocabrillo

2023-11-06 16:36 UTC, bigludo7 commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +                $ref: '#/components/schemas/SubscriptionInfo'
Yes make sense for POST & GET answers --> I've updated.

For POST request, the `phoneNumber` could be optional as we can have it by the network thru Authorization code flow or CIBA flow.

2023-11-13 13:55 UTC, bigludo7 commented
Hello @fernandopradocabrillo @gregory1g @DT-DawidWroblewski Any pending issue preventing to get your approval?
We should probably moving forward with this PR and then use GitHub issue for improving the proposal. Thanks

2023-11-13 13:57 UTC, gregory1g commented
> Any pending issue preventing to get your approval?

nothing from my side.

2023-11-13 15:25 UTC, fernandopradocabrillo commented
> Any pending issue preventing to get your approval?

LGTM from my side too. If we detect something in the future we can always fix it

2023-11-13 15:26 UTC, fernandopradocabrillo submitted a review, later dismissed
LGTM

2023-11-17 11:02 UTC, DT-DawidWroblewski requested changes

2023-11-17 11:02 UTC, DT-DawidWroblewski commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +    RoamingNotificationEventType:
Roaming notification in sim swap API? is it a new enhancement coming with sim swap notification?

2023-11-17 12:31 UTC, bigludo7 commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +    email: project-email@sample.com
Not sure - I followed here what we have in other API but this is a fair question.
My suggestion is to have an issue in Commonalities to have a common rule.

2023-11-17 12:37 UTC, bigludo7 commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +                - notificationsBearerAuth: [ ]
Not sure - I've replicated same thing than in other Subscription API. If we want to provide more we should probably propose someting here: https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#security-considerations

2023-11-17 12:42 UTC, bigludo7 commented on code/API_definitions/sim-swap-notification-subscription.yaml
> +    RoamingNotificationEventType:
ah ah ah ... no :) good catch Dawid. I've wrongly name this class and forget to use it (2 errors on a same line). I fix it.

2023-11-17 12:45 UTC, bigludo7 reviewed
Updated following @DT-DawidWroblewski review.

2023-11-20 11:19 UTC, DT-DawidWroblewski approved these changes
LGTM

2023-11-20 11:19 UTC, merged